# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install 
    
    - run: npm run make --if-present
    
    - run: cd ./out/make; npx tree-cli -l 4 -y
    
    - name: upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: electron-forge-test-linux-x64
        path: ./out/make/deb/x64/*.deb

    - uses: actions/upload-artifact@v3
      with:
        name: electron-forge-test-darwin-arm
        path: ./out/make/zip/darwin/arm64/*.zip

    - uses: actions/upload-artifact@v3
      with:
        name: electron-forge-test-darwin-x64
        path: ./out/make/zip/darwin/x64/*.zip

    - uses: actions/upload-artifact@v3
      with:
        name: electron-forge-test-win-x64
        path: ./out/make/zip/win32/x64/*.zip